import Head from 'next/head'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import Form from '../components/Form'
import About from './About'


export default function Home() {
  return (
    <div className="index">
      <Head>
        <title>Masa-Solat</title>
        <link rel="icon" href="/logo/1.svg" />
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></link>
    
      </Head>
  {/* <Form/> */}
  
  <div className="container-index ">
  <iframe src="https://calculatormasa-sembahyang.netlify.app/" name="myiFrame" className='iframe-index '
frameBorder={0} scrolling="no"
></iframe>
<iframe style={{width: 240, height: 395, border: '1px solid #ddd'}} scrolling="no" src="https://www.islamicfinder.org/specialislamicdays"> </iframe>
  </div>
  
 
 
     {/* <About/> */}
    {/* <Footer/> */}
    </div>
  )
}
